### ISSUE TITLE
don't reset index on dataframes, for future merging

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-pickling#102]
see https://github.com/hassonlab/247-encoding/issues/50

In tfsemb_concat, currently: `pd.concat(all_df, ignore_index=True)`, but we don't want to ignore.

**Comment by hvgazula** [comment]
Replace https://github.com/hassonlab/247-pickling/blob/4588392872b7491a8a7a52cee553968ac025722e/scripts/tfsemb_main.py#L589 with `df = pd.DataFrame(index=df.index)`

**Comment by VeritasJoker** [comment]
So uh I don't think this is resolved. I am regenerating embeddings now for 798 and found out that while we are saving the emb_df into pickles, we are using `to_dict` with "records" here: https://github.com/hassonlab/247-pickling/blob/b7a6fcb060ecb8276b5dcb090b97e6f5b2983558/scripts/tfsemb_main.py#L32

and here:
https://github.com/hassonlab/247-pickling/blob/b7a6fcb060ecb8276b5dcb090b97e6f5b2983558/scripts/tfsemb_main.py#L37

This does not seem to save index, which we need when concatenate
[more here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html)

**Comment by zkokaja** [comment]
But merging on index works in encoding? Should we just use `pd.to_pickle` instead?

**Comment by VeritasJoker** [comment]
Yes merging on index works in encoding. I think `pd.to_pickle` should work?

**Comment by zkokaja** [comment]
Related to #153
