### ISSUE TITLE
failed create-sig-pickle for 777 (podcast)

### ISSUE THREAD

**Issue by leoniekerken** [hassonlab/247-pickling#105]
When trying to create-sig-pickle for 777 (podcast), several errors occurred:

1) In tfspkl_build_matrices.py, line 57: TypeError: read_csv() got an unexpected keyword argument 'columns'
-> pd.read_csv does not take 'columns' as keyword argument, should be changed to 'names' ->https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

2)  In tfspkl_build_matrices.py, line 137: zip* fails to unpack values ->
ValueError: not enough values to unpack (expected 2, got 0)
(this is related to error 3)

3) There seems to be a mismatch between electrode_labels and electrode_names for subject 662 

<img width="986" alt="Screenshot 2022-12-06 at 16 07 12" src="https://user-images.githubusercontent.com/72268792/206023022-fce3b2ea-f493-4900-a9e4-dbededc5bb15.png">

**Comment by hvgazula** [comment]
I think I am still working on fixing this issue. Hopefully, this should be done tonight or by the meeting time tomorrow.

**Comment by hvgazula** [comment]
If possible, could you also paste the command you ran? That will help reproduce the error. Thanks.

**Comment by hvgazula** [comment]
Hye @leoniekerken can you try doing the same with this https://github.com/hassonlab/247-pickling/tree/cf50fafda2c81573d3b8f788bf6f13065ac74890

**Comment by leoniekerken** [comment]
So I tried the same and now make create-sig-pickle for podcast (777) works. However, I do get an error when running make create-pickle for podcast (661):   File "/scratch/gpfs/ln1144/247-pickling/code/tfspkl_utils.py", line 191, in get_electrode_labels
    raise ValueError('Header File Missing')
ValueError: Header File Missing

**Comment by hvgazula** [comment]
Wow..what a mess the code is :)

**Comment by leoniekerken** [comment]
Oh wait... that was my bad - had the wrong specifications in the makefile. Now I corrected it and it worked fine. Sorry!

**Comment by hvgazula** [comment]
Good. Thanks for trying this. Now, we know the source of the error. I will fix it as soon as possible.

**Comment by leoniekerken** [comment]
Thanks!

**Comment by hvgazula** [comment]
Resolved. Duplicates https://github.com/hassonlab/247-pickling/issues/97

**Comment by hvgazula** [comment]
@leoniekerken Did you generate any contextual embeddings (say gpt2), or did you stop with pickling? If yes, do you mind sharing the path to where your embeddings are so I can copy them over and rewrite the targets for copying embeddings?

**Comment by hvgazula** [comment]
Please ignore this request. I am doing this myself.
