### ISSUE TITLE
copy-embeddings in Makefile not updated with pickle hierarchy

### ISSUE THREAD

**Issue by VeritasJoker** [hassonlab/247-pickling#108]
copy-embeddings (used for copying embeddings from podcast/661/pickles to podcast/777/pickles) needs to be updated with the current folder structure

I suggest we just do a simple rsync on the whole 661/pickles/embeddings folder since we don't have naming in the embedding pickles anymore.

**Comment by hvgazula** [comment]
Related https://github.com/hassonlab/247-pickling/issues/50

**Comment by hvgazula** [comment]
Also, (vaguely) depends on https://github.com/hassonlab/247-pickling/pull/65#issuecomment-1356475291
