### ISSUE TITLE
Check if token_idx column is generated correctly

### ISSUE THREAD

**Issue by VeritasJoker** [hassonlab/247-pickling#141]
![Screen Shot 2023-01-11 at 2 47 10 PM](https://user-images.githubusercontent.com/32722770/211905067-c3d7178a-4073-4205-b543-06da462ca827.png)
![Screen Shot 2023-01-11 at 2 48 28 PM](https://user-images.githubusercontent.com/32722770/211905090-5785c834-6c79-4f47-8171-9eb26354353b.png)

**Comment by hvgazula** [comment]
Can you please elaborate?

**Comment by VeritasJoker** [comment]
Oh since I'm testing for different types of choosing tokens to use in encoding, I need the token_idx to be correct (as in representing the token index for each token inside a specific word). The screenshot shows the datum for 625 loaded in encoding, the token_idx doesn't seem to be correct as there are values going as high as 73. So I will check the pickling code to see where this is generated (probably tokenize and explode?)

**Comment by hvgazula** [comment]
Can you try an older commit and check this?

**Comment by VeritasJoker** [comment]
Oh I'm trying your newest commit in dev, which has a new line for the token_idx generation
