### ISSUE TITLE
717 has malformed datums

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-pickling#142]
With words surrounded with asterisks and dashes, which may cause problems for LLMs. Should we handle it differently? Fix the problem upstream?

**Comment by hvgazula** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/9400767/222295712-33b9881b-d51f-4213-8040-afc98ed6483d.png">

**Comment by zkokaja** [comment]
`df.explode('word')` should set `nans` on onsets and offsets for duplicated values so we don't run them in encoding
