### ISSUE TITLE
run into "Error loading omw-1.4: <urlopen error [Errno -2] Name or service not known>" during salloc for "create-sig-pickle" command

### ISSUE THREAD

**Issue by aditis-git** [hassonlab/247-pickling#143]
https://github.com/hassonlab/247-pickling/blob/f36f764f252db99b4dfb225b0931c231e3e8892f/scripts/tfspkl_main.py#L22

**Comment by hvgazula** [comment]
snapshot of the error please

**Comment by hvgazula** [comment]
I guess you are running this target on the compute node which doesn't have internet access. you need to run this on the head node.

**Comment by aditis-git** [comment]
So I’m doing:

salloc --nodes=1 --ntasks=1 —mem=16G --time=00:40:00 

right now (not sure if this is right command for running on the head node)

And immediately I get a the loading error (attached) when I run “make create-sig-pickle”

However, it doesn’t stop — it continues running and aligning for a bit and usually I get a broken pipe error (just running it now and will attach a screenshot shortly!)

<img width="1148" alt="Screenshot 2023-01-25 at 2 47 49 PM" src="https://user-images.githubusercontent.com/22330986/214675833-18587b1d-e3da-412a-8c6c-9b1f8e67f497.png">

**Comment by hvgazula** [comment]
Please run this target on the head node and not the compute node. :)

**Comment by aditis-git** [comment]
Ah..sorry not sure I know the difference -- is the head node basically just running it without the salloc? (and just activate the environment)? I tried that and I ran out of memory after a few participants
