### ISSUE TITLE
error when importing gensim

### ISSUE THREAD

**Issue by aditisinghs** [hassonlab/247-pickling#159]
Hello! 
I get the following error when running pickling (specifically make generate-embeddings) for whisper at line 5:
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/ln1144/.conda/envs/247-main-new/lib/python3.10/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-310-x86_64-linux-gnu.so)

I am using Harsha's environment, so I'm not sure how to resolve this-- I searched online, and does "conda install libgcc" need to be run?

https://github.com/hassonlab/247-pickling/blob/b7a6fcb060ecb8276b5dcb090b97e6f5b2983558/scripts/tfsemb_main.py#L5

**Comment by zkokaja** [comment]
in case it matters, it looks like you're using Leo's not Harsha's environemnt: ` /home/ln1144/.conda`

**Comment by aditisinghs** [comment]
forgot i had been testing leo's environment a while back -- thank you :)
