### ISSUE TITLE
Floats in onset and offset

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#163]
![Screenshot 2023-10-05 at 5 02 22 AM](https://github.com/hassonlab/247-pickling/assets/9400767/1fd3c2e5-8f28-45c8-967f-f99e0c7ae644)

Project ID: tfs
Subject: 625 
File: base_df.pkl

@VeritasJoker Thoughts?

**Comment by VeritasJoker** [comment]
What do you mean? It has always been a float?

**Comment by hvgazula** [comment]
bruh..
