### ISSUE TITLE
Turned off adding vocab columns in LMBase.py

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#171]
@VeritasJoker why did you turn it off?

https://github.com/hassonlab/247-pickling/blob/9dc12c4eb1df99c78a80684b9998da0b809246d0/scripts/tfsemb_LMBase.py#L64

**Comment by VeritasJoker** [comment]
I think for faster generate-base-for-embeddings for running perplexity. Just ignore it
