### ISSUE TITLE
Makefile errors

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-pickling#25]
I have problems running makefile targets. In particular link-data fails with:

```
make: *** No rule to make target `link-data-vars', needed by `link-data'.  Stop.
```

And embeddings target depend on non-existing targets such as `generate-embeddings-variables` and `generate-embeddings-vars`. For example, https://github.com/hassonlab/247-pickling/blob/main/Makefile#L81

**Comment by hvgazula** [comment]
Please remove all dependent targets and it should work fine. Lmk if it doesn't.

**Comment by hvgazula** [comment]
Please pull the new commit and let me know how it goes. Thanks.

**Comment by hvgazula** [comment]
@zkokaja  Were you able to run the link-data target? I am running into 
<img width="932" alt="Screen Shot 2021-04-09 at 11 47 27 AM" src="https://user-images.githubusercontent.com/9400767/114206465-5ee97880-9929-11eb-91e7-5eaea68b4ac6.png">
permission errors now. Were the permission on /projects changed?

**Comment by zkokaja** [comment]
Thanks, I'll test and let you know. I haven't changed any permissions.

**Comment by zkokaja** [comment]
One additional problem: https://github.com/hassonlab/247-pickling/blob/main/Makefile#L8 should have no space after last character and the first comment hashtag, because this happens:

```
ln -sf /projects/HASSON/247/data/conversations-car/* data/tfs /
```

It tries to link everything to `/`.

**Comment by hvgazula** [comment]
Forgot to push the changes. Please check the new commit https://github.com/hassonlab/247-pickling/tree/658bc3ad4821d884a5f0cc3034f7fce5d35e31b6 and close the issue if it works fine.
