### ISSUE TITLE
copy-embeddings make target vs  python script

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#50]
If the copy-embeddings target replaces the tfspkl_copy.py, then I reckon we should just delete the python script. Also, probably `ln -s` is better instead of cp to save space. What do you think @zkokaja?

**Comment by zkokaja** [comment]
Good idea! How would it affect uploading to gcp? Either way it seems it can be in bash instead of python

**Comment by hvgazula** [comment]
indeed

**Comment by hvgazula** [comment]
deleted tfspkl_copy.py as the make target 'copy-embeddings' takes care of it
