### ISSUE TITLE
Is 'generate_embeddings' a redundant function?

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#52]
@zkokaja @VeritasJoker Any idea why we have [this](https://github.com/hassonlab/247-pickling/blob/main/scripts/tfsemb_main.py#L597) function? Looking at this [part](https://github.com/hassonlab/247-pickling/blob/main/scripts/tfsemb_main.py#L597) of the `main` function, it looks like we have function calls for glove, blenderbot, and all other causalLM models. So, I think the aforementioned function is redundant? Please clarify.

**Comment by hvgazula** [comment]
Likewise `args.history` feels redundant now? What do you think?

**Comment by hvgazula** [comment]
comments?

**Comment by VeritasJoker** [comment]
I don't think I see the function used anywhere, so yeah seems like it

**Comment by hvgazula** [comment]
https://github.com/hassonlab/247-pickling/commit/378447b2c21572b839889377498581123496fd83
