### ISSUE TITLE
Add rank for correct prediction

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#56]
https://github.com/hassonlab/247-pickling/blob/main/code/tfsemb_main.py#L577

**Comment by hvgazula** [comment]
duplicate

**Comment by hvgazula** [comment]
done.. verified @VeritasJoker  :)

**Comment by VeritasJoker** [comment]
Yeah about that, I'm not sure if it's working for now. Can we leave this open? Might need further testing.

![Screen Shot 2022-10-26 at 7 47 01 PM](https://user-images.githubusercontent.com/32722770/198160105-09eb5516-bf16-4868-a552-00d2d9d78487.png)
