### ISSUE TITLE
check_token_is_root() vs add_vocab_columns().. are they the same?

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#73]
the first one comes form tfsemb_main.py and the latter come from tfspkl_main

**Comment by zkokaja** [comment]
What is the issue exactly? Please create MWE @hvgazula

**Comment by zkokaja** [comment]
What is the difference between these two implementations:

```
def calc_tokenizer_length(tokenizer, word):
    return False if pd.isnull(word) else len(tokenizer.tokenize(word)) == 1
```

vs

```
def check_token_is_root(args, df):
    token_is_root_string = args.embedding_type.split("/")[-1] + "_token_is_root"
    df[token_is_root_string] = (
        df["word"]
        == df["token"].apply(args.tokenizer.convert_tokens_to_string).str.strip()
    )

    return df
```

**Comment by hvgazula** [comment]
@zkokaja and @hvgazula decided to replace  `calc_tokenizer_length` in `tfspkl_main.py` with `check_token_is_root()` from `tfsemb_main.py`

**Comment by zkokaja** [comment]
Now we just check if the word/token (glove/LM) is in other models:
https://github.com/hassonlab/247-pickling/blob/main/scripts/tfsemb_LMBase.py#L38-L40
