### ISSUE TITLE
creating environment from requirements.yml failed

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#78]
found this while working with @zkokaja

**Comment by hvgazula** [comment]
remove all torch related lines in yml file and then install them later.

**Comment by hvgazula** [comment]
@hvgazula Create a make target with 1. pip install -f reks.txt and 2. pip install pytorch

**Comment by zkokaja** [comment]
Use Harsha's environment. @hvgazula find a way to update everyone when you change the environment

**Comment by hvgazula** [comment]
https://github.com/hassonlab/247-main/issues/15#issuecomment-1190537359

fix: https://stackoverflow.com/questions/2477117/pip-requirements-txt-with-alternative-index

**Comment by hvgazula** [comment]
I didn't really find a way to track virtual environment transactions (like conda history). Probably, the onus is on each of us to run `pip list`. But otherwise, sharing one person's env (with no install rights) sort of automatically forces the maintainer to ensure the environment is intact.
