### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-pickling#80]
PR into dev0.1 branch

1. new conda/pip environment (upgrade python version, etc.)
2. split base labels from embeddings into separate pickles, instead of coupled. 
3. electrode/signal extraction for 625/676 vs 717 (nans based on convs) #46
5. embeddings for LLMs (OPT, GPT-NEOX) <= 6.7B
6. pickle output folder structure changes

Address following issues:
- #77
- #76 
- #56

**Comment by hvgazula** [comment]
All done and in https://github.com/hassonlab/247-pickling/tree/dev_branch

**Comment by zaidzada** [comment]
This also includes changes that will extract _all_ electrodes, padding a signal, in_model columns moved to a different script.

**Comment by zkokaja** [comment]
@hvgazula  Remove line 21 from tfsemb_LMBase and then we can merge!
