### ISSUE TITLE
Folds in pickling

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-pickling#90]
https://github.com/hassonlab/247-pickling/blob/2fa1ef112ec80af92b5d78b2903daee130fb20ec/scripts/tfspkl_parser.py#L26

What are the challenges with creating folds in pickling instead of encoding? aka, preprocessing and then folds vs folds and then preprocessing.

**Comment by zkokaja** [comment]
A lot of filtering is happening in 247-encoding that sub selects data before creating folds
